name: triviapenguin
services:
  be:
    container_name: triviapenguin-be
    build:
      context: ./backend
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL} # note: use db service internal port!
      DATASOURCE_USER: ${DATASOURCE_USER} 
      DATASOURCE_PASS: ${DATASOURCE_PASS}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - app_network
  fe:
    container_name: triviapenguin-fe
    build:
      context: ./frontend
    volumes:
      - shared-data:/usr/share/nginx/html
    networks:
      - app_network
  db:
    container_name: triviapenguin-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATASOURCE_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASS}
    ports:
      # external:internal
      - "5445:5432"
    networks:
      - app_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  proxy:
    container_name: triviapenguin-proxy
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - shared-data:/usr/share/nginx/html
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - fe
      - be
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  shared-data:
  postgres-data:
