name: triviapenguin
services:
  be:
    container_name: triviapenguin-be
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL} # note: use db service internal port!
      DATASOURCE_USER: ${DATASOURCE_USER} 
      DATASOURCE_PASS: ${DATASOURCE_PASS}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
  fe:
    container_name: triviapenguin-fe
    build:
      context: ./frontend
    ports:
      - "80:80"
  db:
    container_name: triviapenguin-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATASOURCE_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASS}
    ports:
      # external:internal
      - "5445:5432"
