services: 
  db:
    container_name: quiz-app-db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      # external:internal
      - "5445:5432"
 